<div data-importer="border">
  <img style="100%" src="https://capsule-render.vercel.app/api?type=waving&height=120&section=header&reversal=false&text=BENJAMIN%E2%80%8E%20%E2%80%8E%20J%20%E2%80%8E%20ALANI&fontSize=45&fontColor=FFFF00&fontAlign=50&fontAlignY=50&stroke=-&animation=twinkling&desc=BCA%20GRADUATE%20%20%E2%80%8E%20%20%E2%80%8E%20%E2%80%A2%20%20%E2%80%8E%20%E2%80%8E%20%20CREATIVE%20%20%E2%80%8E%E2%80%8E%20%20%20%E2%80%A2%20%E2%80%8E%20%E2%80%8E%20%20%20FULL-STACK&descSize=11&descAlign=50&descAlignY=80&textBg=false&color=gradient"  />
</div>

###

<div data-importer="profile-views" align="center">
  <img data-importer="profile-views" src="https://count.getloli.com/@:maurodesouza?theme=gelbooru&padding=5&offset=05&scale=1&align=top&pixelated=1&darkmode=auto"/>
</div>

###

<picture data-importer="pacman">
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/maurodesouza/maurodesouza/pacman-output/pacman-contribution-graph-dark.svg?game=pacman">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/maurodesouza/maurodesouza/pacman-output/pacman-contribution-graph.svg?game=pacman">
  <img alt="pacman contribution graph" src="https://raw.githubusercontent.com/maurodesouza/maurodesouza/pacman-output/pacman-contribution-graph.svg?game=pacman">
</picture>

###

<div data-importer="socials" align="center">
  <a href="https://in.linkedin.com/in/benjamin-j-8282b42a3" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/linkedin/default.svg" width="52" height="40" alt="linkedin logo"  />
  </a>
  <a href="https://x.com/" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/twitter/default.svg" width="52" height="40" alt="twitter logo"  />
  </a>
  <a href="https://t.me/+fBG_qfs47UNlMzk1" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/spotify/default.svg" width="52" height="40" alt="spotify logo"  />
  </a>
  <a href="mailto:benjaminjalany@gmail.com" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/gmail/default.svg" width="52" height="40" alt="gmail logo"  />
  </a>
  <a href="https://www.benjaminjalani.in/" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/linktree/default.svg" width="52" height="40" alt="linktree logo"  />
  </a>
</div>

###
